### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [elorest/CRelease#1]
Hello,

I've checked your project and it either:

* Has specs failed with the latest Crystal (0.26.1)
* Has no any specs to run so it cannot be validated to be up to date
* Has the latest commit dated more than a year ago

Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by elorest** [comment]
This was maintained as of 0.25. Myself and many others still use this. I'll
look into whether or not it works for 0.26.

**Comment by vladfaust** [comment]
Thanks for the response!

**Comment by elorest** [comment]
I just checked and it compiles in 0.26.0.

**Comment by vladfaust** [comment]
It may be some issues with my system IDK. However, thanks for updating! Note that you can set up daily/weekly tests on Travis so you'll receive a notification when the build begins to fail: https://docs.travis-ci.com/user/cron-jobs.
